# Model arguments
model_name_or_path: Qwen/Qwen2.5-Coder-7B
output_dir: ckpt/Qwen_dpo_ep2_59k_bs128_beta1_alpha1
torch_dtype: null

dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 96

# DPOTrainer arguments
# gbs 128
bf16: true
beta: 0.1
# do_eval: true
# eval_strategy: steps
# eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1024
num_train_epochs: 2
optim: adamw_torch_fused
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: False
save_strategy: "steps"
save_steps: 100
save_total_limit: 50
seed: 42
warmup_ratio: 0.03
rpo_alpha: 1.0
report_to:
- wandb